development:
  adapter: postgresql
  encoding: unicode
  database: receta_development
  pool: 5
  username: dszromik
  password: dszromik
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: receta_test
  pool: 5
  username: dszromik
  password: dszromik
  host: localhost
  port: 5432
